language: java
env:
  global:
  #CODACY_API_TOKEN
  - secure: wLy4zmfFUKqdLkQJOqPkUbaBwatF6kKsb4aT/wFsLyrm4rCZ2P6r/O5FXOBCviVyhOdRwJn0lg6xsuM+mD61w3giQVjBgVSTpka1MOYp24kCmm771NewRhvnDKYVJ0P0ugqy2OQupZ9AEA+X8+TDiiz6qGOccJp6zDZ0TlE7BPNFCwp7aZ3Z9xxXvAT30VdsS3tSngeHbxPhO7zy9p14kAlwIa3UGgzrLOk5RNUwI1hXQYBeJLvbITGlRjJVRZxlQjCqVdZnQBBIiAflINYHVG1rWlviNowu4vMaSLfbE6Vs8bzKb0NLVpRFdDN11HSY6FM1Z8T52bIb5gagkx3b25ybUpieWZ/mAWyK+a2sS3gI+i6HelAU9rj1diVSV9s0EEBT+iikPeDQf/dWTwXsE5Wn8LiR56MrgCpbm1FUhq26MXj7NoQjWfrybjU2Ncvya8plzIB5fB2CVpl7HeiJuX/sJG9a+FkDEREp/mdd1tjoCZXr06zUHXPi7AqmoGcRX/M9dIKHDUyG8uvEnqioN/L+BQz4uAnxoul6DgWOrbC/twD5XtXigWjOzo6LqzhJceX79MysrSweFLej17VTQ+KqUDaJ1u9wNhkFO1D95GXR+lMKIjMzev7X+SGhpiu3erxPie5VabThySGx9b/U8Ey83LFx5k0vgLeKrh3gy3Q=
  #CODACY_PROJECT_TOKEN
  - secure: qO3g2us7Q7DVdDk9JXWZ/sA+XmvNgNTHNZaCa2OYc8XQ8s6RG1RCVb8FC2ciWgPBJP6EHW1t7g3uK6JmRNNwgZX7bWih3GByH3yNw5qYcD0Uc5xc25vYW84MrSTc52p1i1IOAWvor2XjUi698t2/pwt+P8vgdWJX/iNRE6AKosb55YS5c/LeFU+lan3zVSqr2di1vlfQCqijeG4gB5gYmq39uYAhIcMOZbfST1bA3MjqscnLWrYnFr/R2FtctdadGeJ8zjE1RjHyTHHlM4MBr5v3b07pSFRO4fp42Fhx2bzzE/QE1WSFnAPVmUKvX5ZZ9OqaHQDakCdQYk0pmyjKNrrlNFuqX8QTzTy7d/VAgzEGRAjq+hqUXNePWf6cWBoq2HMcrYjNU5Sdkz32cimDR9X0+3wDYuRSm5zyknauboQtMzII6MJSDXnv/m/IV3AoB5Meumq+8wgZ/TWsS9QXB2vYXHtlRNER6NypZhAk/NB6wk4C2MbdXPdoTZhpS7OjXFb/yhIGgRpliRnPDOFbEC1Nhe7KDMHS/ucsO9NOKSNkJ4BgSECWWOoP8wZPHZthmgJWLZFEY2fQAwmAkElYYE2pzOW5WSUfHdkIaqAz21CnrlcxEp2i/Qk5sPja0uVigr7C0UL7NJw+ASZqky7opwnxyQLmzy5IR60x1kGwx3g=

os: linux
dist: yaketty
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

script:
  - mvn clean
  - mvn test -B
  - mvn versioneye:update
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_API_TOKEN
